filter:
    excluded_paths:
        - tests/*
        - vendor/*

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        redis: false
        docker: true

    dependencies:
        override:
            - docker-compose up -d --remove-orphans --build
            - docker-compose exec -T php /usr/local/bin/php /usr/local/bin/composer install

    nodes:
        coverage:
            tests:
                override:
                    -   command: docker-compose run --rm -T php /usr/local/bin/php /app/vendor/bin/phpunit --coverage-clover=coverage.xml
                        coverage:
                            file: coverage.xml
                            format: clover
